[project]
entry = "abi.sw"
license = "Apache-2.0"
name = "market_abi"

[dependencies]
i256 = { path = "../../libs/i256" }
pyth_interface = { git = "https://github.com/pyth-network/pyth-crosschain", tag = "pyth-fuel-contract-v0.5.0" }
